# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Fortify on Ubuntu'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: FortifySCA@6
  inputs:
    runBuildTranslate: true
    applicationType: 'java'
    fortifyBuildId: 'insecureforum'
    runFortifyRulepackUpdate: false
    runFortifyClean: true
    scaVerbose: false
    scaDebug: false
    runFortifyScan: true
    fortifyScanType: 'Local'