# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:   
  build:
    
    runs-on: fortify
    
    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: 
        mvn -B package --file pom.xml
    - name: Fortify Scan
      run: |
       mvn com.fortify.sca.plugins.maven:sca-maven-plugin:20.2.0:translate
       mvn com.fortify.sca.plugins.maven:sca-maven-plugin:20.2.0:scan
    - name: Fortify Scan Result Upload
      run: 
       fortifyclient -url ${{ secrets.SSCURL }} -authtoken  ${{ secrets.ANALYSISUPLOADTOKEN }} uploadFPR -file ${{ secrets.PATH_TO_FPR }} -applicationVersionID ${{ secrets.APP_VER_ID }}

  downloadscan:
    needs: build
    runs-on: fortify
    steps:
      - name: Powershell request
        run: |
          sleep -s 30
          $getresp = Invoke-RestMethod -Uri 'http://192.168.45.133:8080/ssc/api/v1/projectVersions/10000/issues?start=0&limit=200&showhidden=false&showremoved=false&showsuppressed=false&showshortfilenames=false' -Headers @{ 'Authorization' = 'FortifyToken YzMyMTliOGUtMmQ3ZC00NzY3LTk0MzItNjZkNzA0NWJmMDNj '  }
          echo $getresp.count
          if ( $getresp.count -gt 0 ) { exit(1) }
          shell: pwsh
