# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:   
  Build And Perform Fortify Scan:
    
    runs-on: fortify
    
    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: 
        mvn -B package --file pom.xml
    - name: Fortify Scan
      run: |
       mvn com.fortify.sca.plugins.maven:sca-maven-plugin:20.2.0:translate
       mvn com.fortify.sca.plugins.maven:sca-maven-plugin:20.2.0:scan
    - name: Fortify Scan Result Upload
      run: 
       fortifyclient -url ${{ secrets.SSCURL }} -authtoken  ${{ secrets.ANALYSISUPLOADTOKEN }} uploadFPR -file ${{ secrets.PATH_TO_FPR }} -applicationVersionID ${{ secrets.APP_VER_ID }}

  Download Scan Results:
    needs: Build And Perform Fortify Scan
    runs-on: fortify
    steps:
      - name: Download Scan Results from SSC
        run: |
          sleep -s 30
          $getresp = Invoke-RestMethod -Uri '${{ secrets.SSCAPIURL }}' -Headers @{ 'Authorization' = '${{ secrets.SSCAPITOKEN }}'  }
          if ( $getresp.data.folderId -eq 1 ) 
          { 
            Write-Output "Critial issues are identified in the fortify scan result! Hence, failing the workflow"; exit (1)
          }
